package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"sort"

	"github.com/bobTheBuilder7/pgen/syncmap"
	"github.com/bobTheBuilder7/pgen/utils"
)

type enumDef struct {
	PgName string
	GoName string
	Values []enumValue
}

type enumValue struct {
	Label   string
	GoValue string
}

func enumDefsFromMap(m *syncmap.Map[string, []string]) []enumDef {
	var names []string
	m.Range(func(k string, _ []string) bool {
		names = append(names, k)
		return true
	})
	sort.Strings(names)

	var defs []enumDef
	for _, name := range names {
		vals, _ := m.Load(name)
		def := enumDef{
			PgName: name,
			GoName: utils.ToPascalCase(name),
		}
		for _, v := range vals {
			def.Values = append(def.Values, enumValue{
				Label:   v,
				GoValue: utils.ToPascalCase(v),
			})
		}
		defs = append(defs, def)
	}
	return defs
}

func generateModelsFile(w io.Writer, m *syncmap.Map[string, []string]) error {
	defs := enumDefsFromMap(m)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by pgen. DO NOT EDIT.\n\n")
	buf.WriteString("package db\n\n")

	if len(defs) > 0 {
		buf.WriteString("import (\n\t\"database/sql/driver\"\n\t\"fmt\"\n)\n\n")
	}

	for _, e := range defs {
		fmt.Fprintf(&buf, "type %s string\n\n", e.GoName)

		fmt.Fprintf(&buf, "const (\n")
		for _, v := range e.Values {
			fmt.Fprintf(&buf, "\t%s%s %s = %q\n", e.GoName, v.GoValue, e.GoName, v.Label)
		}
		fmt.Fprintf(&buf, ")\n\n")

		fmt.Fprintf(&buf, "func (e *%s) Scan(src interface{}) error {\n", e.GoName)
		fmt.Fprintf(&buf, "\tswitch s := src.(type) {\n")
		fmt.Fprintf(&buf, "\tcase []byte:\n")
		fmt.Fprintf(&buf, "\t\t*e = %s(s)\n", e.GoName)
		fmt.Fprintf(&buf, "\tcase string:\n")
		fmt.Fprintf(&buf, "\t\t*e = %s(s)\n", e.GoName)
		fmt.Fprintf(&buf, "\tdefault:\n")
		fmt.Fprintf(&buf, "\t\treturn fmt.Errorf(\"unsupported scan type for %s: %%T\", src)\n", e.GoName)
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\treturn nil\n")
		fmt.Fprintf(&buf, "}\n\n")

		fmt.Fprintf(&buf, "type Null%s struct {\n", e.GoName)
		fmt.Fprintf(&buf, "\t%s %s `json:%q`\n", e.GoName, e.GoName, e.PgName)
		fmt.Fprintf(&buf, "\tValid    bool `json:\"valid\"`\n")
		fmt.Fprintf(&buf, "}\n\n")

		fmt.Fprintf(&buf, "// Scan implements the Scanner interface.\n")
		fmt.Fprintf(&buf, "func (ns *Null%s) Scan(value interface{}) error {\n", e.GoName)
		fmt.Fprintf(&buf, "\tif value == nil {\n")
		fmt.Fprintf(&buf, "\t\tns.%s, ns.Valid = \"\", false\n", e.GoName)
		fmt.Fprintf(&buf, "\t\treturn nil\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tns.Valid = true\n")
		fmt.Fprintf(&buf, "\treturn ns.%s.Scan(value)\n", e.GoName)
		fmt.Fprintf(&buf, "}\n\n")

		fmt.Fprintf(&buf, "// Value implements the driver Valuer interface.\n")
		fmt.Fprintf(&buf, "func (ns Null%s) Value() (driver.Value, error) {\n", e.GoName)
		fmt.Fprintf(&buf, "\tif !ns.Valid {\n")
		fmt.Fprintf(&buf, "\t\treturn nil, nil\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\treturn string(ns.%s), nil\n", e.GoName)
		fmt.Fprintf(&buf, "}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting models file: %w", err)
	}
	_, err = w.Write(formatted)
	return err
}
